### ISSUE TITLE
Is this still api supported?

### ISSUE THREAD

**Issue by RiceRiceBaby** [jrquick17/ng-speed-test#37]
Is this api still supported? I cannot get it to work on Angular 9+. I'm getting the following error:

Compiling ng-speed-test : module as esm5
Warning: Invalid constructor parameter decorator in /Users/562059/Documents/new-gateway/node_modules/ng-speed-test/fesm2015/ng-speed-test.js:
 () => []
Error: Error on worker #1: Error: getInternalNameOfClass() called on a non-ES5 class: expected SpeedTestService to have an inner class declaration
    at Esm5ReflectionHost.getInternalNameOfClass (/Users/562059/Documents/new-gateway/node_modules/@angular/compiler-cli/ngcc/src/host/esm5_host.js:88:23)
    at DelegatingReflectionHost.getInternalNameOfClass (/Users/562059/Documents/new-gateway/node_modules/@angular/compiler-cli/ngcc/src/host/delegating_host.js:89:34)
    at extractInjectableMetadata (/Users/562059/Documents/new-gateway/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/injectable.js:125:69)
    at InjectableDecoratorHandler.analyze (/Users/562059/Documents/new-gateway/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/injectable.js:66:24)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (/Users/562059/Documents/new-gateway/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:345:40)
    at analyze (/Users/562059/Documents/new-gateway/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:297:58)
    at _loop_1 (/Users/562059/Documents/new-gateway/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:319:21)
    at NgccTraitCompiler.TraitCompiler.analyzeClass (/Users/562059/Documents/new-gateway/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:325:35)
    at NgccTraitCompiler.analyzeFile (/Users/562059/Documents/new-gateway/node_modules/@angular/compiler-cli/ngcc/src/analysis/ngcc_trait_compiler.js:47:26)
    at DecorationAnalyzer.analyzeProgram (/Users/562059/Documents/new-gateway/node_modules/@angular/compiler-cli/ngcc/src/analysis/decoration_analyzer.js:134:39)
    at ClusterMaster.onWorkerMessage (/Users/562059/Documents/new-gateway/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:194:27)
    at /Users/562059/Documents/new-gateway/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:54:95
    at ClusterMaster.<anonymous> (/Users/562059/Documents/new-gateway/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:292:57)
    at step (/Users/562059/Documents/new-gateway/node_modules/tslib/tslib.js:139:27)
    at Object.next (/Users/562059/Documents/new-gateway/node_modules/tslib/tslib.js:120:57)
    at /Users/562059/Documents/new-gateway/node_modules/tslib/tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/562059/Documents/new-gateway/node_modules/tslib/tslib.js:109:16)
    at EventEmitter.<anonymous> (/Users/562059/Documents/new-gateway/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:286:32)
    at EventEmitter.emit (events.js:315:20)
/Users/562059/Documents/new-gateway/node_modules/webpack-cli/bin/cli.js:281
                                throw err;

**Comment by jrquick17** [comment]
Appears to work fine when including `ng-speed-test@^2.3.2` in the dependency array
